package com.lordsai.lsi.entity;

import com.lordsai.lsi.entity.enums.PaymentStatus;
import com.lordsai.lsi.entity.enums.ProductType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;

/**
 * One invoice per successful payment, for every product type. The invoice number is generated by
 * the backend (LSI-INV-YYYY-NNNNNN), is unique and is never changed. Customer/product columns are
 * a snapshot of what was printed, so a later rename or price change never rewrites history.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "invoices", indexes = {
        @Index(name = "idx_invoices_number", columnList = "invoice_number", unique = true),
        @Index(name = "idx_invoices_student", columnList = "student_user_id"),
        @Index(name = "idx_invoices_email", columnList = "student_email"),
        @Index(name = "idx_invoices_product", columnList = "product_type, course_id, ebook_id"),
        @Index(name = "idx_invoices_invoice_date", columnList = "invoice_date"),
        @Index(name = "idx_invoices_purchase", columnList = "purchase_date"),
        @Index(name = "idx_invoices_transaction", columnList = "transaction_id")
})
public class Invoice extends BaseEntity {

    @Column(name = "invoice_number", nullable = false, length = 30)
    private String invoiceNumber;

    @OneToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "payment_id", nullable = false, unique = true)
    private Payment payment;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "student_user_id", nullable = false)
    private User student;

    @Enumerated(EnumType.STRING)
    @Column(name = "product_type", nullable = false, length = 20)
    private ProductType productType;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "course_id")
    private Course course;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ebook_id")
    private Ebook ebook;

    // ---- snapshot ------------------------------------------------------------------------

    @Column(name = "student_name", nullable = false, length = 150)
    private String studentName;

    /** The human Student ID (LSI-YYYY-NNNNN) at the time of purchase. */
    @Column(name = "student_code", length = 20)
    private String studentCode;

    @Column(name = "student_email", nullable = false, length = 190)
    private String studentEmail;

    @Column(name = "student_phone", length = 20)
    private String studentPhone;

    @Column(name = "product_name", nullable = false, length = 200)
    private String productName;

    @Column(nullable = false)
    private int quantity = 1;

    @Column(name = "unit_price", nullable = false, precision = 10, scale = 2)
    private BigDecimal unitPrice;

    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal subtotal;

    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal discount = BigDecimal.ZERO;

    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal tax = BigDecimal.ZERO;

    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal total;

    @Column(nullable = false, length = 3)
    private String currency = "INR";

    @Column(name = "payment_method", length = 40)
    private String paymentMethod;

    /** Razorpay payment id (or the demo marker). */
    @Column(name = "transaction_id", length = 64)
    private String transactionId;

    @Column(name = "order_ref", length = 40)
    private String orderRef;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_status", nullable = false, length = 20)
    private PaymentStatus paymentStatus;

    @Column(name = "invoice_date", nullable = false)
    private LocalDate invoiceDate;

    @Column(name = "purchase_date", nullable = false)
    private Instant purchaseDate;

    @Column(length = 500)
    private String notes;

    // ---- generated file / delivery -------------------------------------------------------

    @Column(name = "pdf_path", length = 255)
    private String pdfPath;

    @Column(name = "pdf_generated_at")
    private Instant pdfGeneratedAt;

    @Column(name = "emailed_at")
    private Instant emailedAt;

    @Column(name = "email_count", nullable = false)
    private int emailCount = 0;

    public Long productId() {
        return productType == ProductType.COURSE
                ? (course == null ? null : course.getId())
                : (ebook == null ? null : ebook.getId());
    }

    public String fileName() {
        return invoiceNumber + ".pdf";
    }
}
